#!/bin/bash
# 🚀 快速啟動腳本 - 睡眠追蹤系統多頁面應用

echo "╔════════════════════════════════════════════════════════╗"
echo "║  🌙 睡眠追蹤系統 - 多頁面應用啟動指南  🌙            ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "📱 新增功能："
echo "  ✅ 儀表板頁面 (Dashboard)"
echo "  ✅ 歷史紀錄頁面 (History)"
echo "  ✅ 設定頁面 (Settings)"
echo "  ✅ 統一導航系統"
echo "  ✅ 響應式設計 (RWD)"
echo ""
echo "🎯 快速測試方法："
echo ""
echo "  方法 1: Python 3 (推薦)"
echo "  ─────────────────────────"
echo "  $ cd frontend"
echo "  $ python -m http.server 8000"
echo "  訪問: http://localhost:8000"
echo ""
echo "  方法 2: Node.js"
echo "  ─────────────────────────"
echo "  $ npm install -g http-server"
echo "  $ cd frontend"
echo "  $ http-server"
echo "  訪問: http://localhost:8080"
echo ""
echo "  方法 3: PHP (如果已安裝)"
echo "  ─────────────────────────"
echo "  $ cd frontend"
echo "  $ php -S localhost:8000"
echo "  訪問: http://localhost:8000"
echo ""
echo "📋 頁面導覽:"
echo "  🏠 首頁    → http://localhost:8000"
echo "  📊 儀表板 → http://localhost:8000/pages/dashboard.html"
echo "  📋 歷史   → http://localhost:8000/pages/history.html"
echo "  ⚙️ 設定   → http://localhost:8000/pages/settings.html"
echo ""
echo "📱 測試響應式設計:"
echo "  按 F12 開啟開發者工具"
echo "  切換設備工具列 (Ctrl+Shift+M 或 Cmd+Shift+M)"
echo "  測試尺寸:"
echo "    • 行動版 (375px, 540px)"
echo "    • 平板版 (768px, 1024px)"
echo "    • 桌面版 (1440px, 1920px)"
echo ""
echo "🧪 測試清單:"
echo "  詳見: TEST_CHECKLIST.md"
echo ""
echo "📖 完整文件:"
echo "  • PAGES_GUIDE.md - 頁面架構詳細說明"
echo "  • TEST_CHECKLIST.md - 測試驗證清單"
echo "  • DASHBOARD_COMPLETION.md - 完成報告"
echo ""
echo "🎨 設計特色:"
echo "  • 紫色漸層主題 (#667eea → #764ba2)"
echo "  • 卡片式布局"
echo "  • 流暢的動畫過渡"
echo "  • 無障礙設計 (WCAG AA)"
echo "  • 觸控友善按鈕 (44×44px)"
echo ""
echo "✨ 已完成功能:"
echo "  ✅ 儀表板統計 (4 個指標卡片)"
echo "  ✅ 歷史紀錄篩選和匯出"
echo "  ✅ 應用設定管理"
echo "  ✅ 統一導航菜單"
echo "  ✅ 漢堡菜單 (行動版)"
echo "  ✅ 完整響應式設計"
echo "  ✅ localStorage 自動儲存"
echo "  ✅ CSV/JSON 資料匯出"
echo ""
echo "💡 提示:"
echo "  • 儀表板需要先設定鬧鐘和追蹤資料"
echo "  • 設定自動儲存到瀏覽器 localStorage"
echo "  • 歷史紀錄中的日期預設為最近 30 天"
echo "  • 按 Ctrl+Shift+Delete 清除 localStorage (測試用)"
echo ""
echo "🆘 常見問題:"
echo "  Q: 導航菜單無法顯示？"
echo "  A: 確認 CSS 文件路徑正確，檢查瀏覽器主控台錯誤"
echo ""
echo "  Q: 設定無法保存？"
echo "  A: 檢查瀏覽器是否允許 localStorage（私密模式不支援）"
echo ""
echo "  Q: 如何測試行動版？"
echo "  A: 按 F12 開發者工具 → Ctrl+Shift+M 切換設備工具列"
echo ""
echo "════════════════════════════════════════════════════════"
echo "準備好了？現在就開始測試吧！ 🚀"
echo "════════════════════════════════════════════════════════"
